framgia/fbook_api

app/Repositories/BookRepositoryEloquent.php
change key user_reading_book Array -> Object
=> Fix response api detail book

app/Contracts/Repositories/UserRepository.php, app/Http/Controllers/Api/BookController.php, app/Http/Controllers/Api/HomeController.php, app/Http/Controllers/Api/UserController.php, app/Http/Requests/Api/Book/StoreRequest.php, app/Repositories/BookRepositoryEloquent.php, app/Repositories/UserRepositoryEloquent.php, routes/api.php, tests/Feature/ControllerTests/Api/UserTest.php
- Add owner key to response api:
-  - get book by session
-  - filter book in home and session
- Fix endpoint waiting approve: change user/books/approved ===> user/books/waiting-approve
- Fix add book: remove code in request and random code
=> Add owner to response, fix add book and endpoint waiting approve

app/Http/Controllers/Api/CategoryController.php, app/Http/Requests/Api/Category/CreateCategoryRequest.php, app/Repositories/CategoryRepositoryEloquent.php, config/settings.php, routes/api.php
Remove unuse class
Add new admin account
=> Create add category function

app/Http/Controllers/Api/CategoryController.php, app/Repositories/CategoryRepositoryEloquent.php, routes/api.php
=> Create edit category function

app/Http/Controllers/Api/ReviewController.php, app/Repositories/MediaRepositoryEloquent.php, routes/api.php
Add book detail to view-review
=> Edit view review UI

app/Eloquent/Comment.php
=> fix time ago

app/Eloquent/Book.php, app/Repositories/BookRepositoryEloquent.php
https://dev.framgia.com/redmine/issues/162312
=> fix sort book detail

app/Eloquent/Category.php, app/Http/Controllers/Api/BookController.php, app/Http/Controllers/Api/CategoryController.php, app/Repositories/CategoryRepositoryEloquent.php, database/migrations/2018_03_16_083951_update_name_jp_and_en_to_categories_table.php
https://dev.framgia.com/redmine/issues/164511
=> add name_en_name_vi to category

app/Repositories/BookRepositoryEloquent.php
https://dev.framgia.com/redmine/issues/165582
=> fixapprove

database/migrations/migration/2018_03_16_083951_update_name_jp_and_en_to_categories_table.php
- Run:  php artisan migrate --path=/app/database/migrations/migration
=> one specific migration

app/Contracts/Repositories/BookRepository.php, app/Http/Controllers/Api/BookController.php, app/Repositories/BookRepositoryEloquent.php
https://dev.framgia.com/redmine/issues/166754
=> api search bar

app/Http/Controllers/Api/HomeController.php, app/Repositories/OwnerRepositoryEloquent.php, config/database.php, config/model.php
https://dev.framgia.com/redmine/issues/166761
=> refs task #166761 Add hot user

app/Http/Controllers/Api/CategoryController.php, app/Repositories/CategoryRepositoryEloquent.php, routes/api.php
link redmine: https://dev.framgia.com/redmine/issues/168761
=> api_update_category_admin

app/Http/Controllers/Api/BookController.php, app/Http/Controllers/Api/HomeController.php
https://dev.framgia.com/redmine/issues/169869
=> refs task #169869 Add category for book

config/settings.php, database/migrations/specific_migration/2018_05_07_111639_add_reputation_point_to_users_table.php, database/migrations/specific_migration/2018_05_07_143933_add_added_to_owners_table.php
Task thêm trường "reputation point" vào bảng users: 
https://dev.framgia.com/redmine/issues/171266
Task thêm trường "added" vào bảng owners: 
https://dev.framgia.com/redmine/issues/171270
=> refs task #171266 [API] Add reputation to user

app/Repositories/BookRepositoryEloquent.php
https://dev.framgia.com/redmine/issues/171273
=> refs task #171273 Link to book info in Admin

app/Contracts/Repositories/UserRepository.php, app/Contracts/Repositories/VoteRepository.php, app/Http/Controllers/Api/ReviewController.php, app/Repositories/UserRepositoryEloquent.php, app/Repositories/VoteRepositoryEloquent.php, config/model.php
https://dev.framgia.com/redmine/issues/171272
=> refs task #171272 Add point to Reviewer

app/Eloquent/Notification.php, app/Eloquent/UserFollow.php, app/Repositories/UserRepositoryEloquent.php, config/model.php, database/migrations/user_follow/2018_05_17_083427_add_soft_delete_to_user_follow.php
https://dev.framgia.com/redmine/issues/172803
=> refs task #172803 Add point when other user follow

app/Eloquent/Book.php, app/Eloquent/Owner.php, app/Eloquent/User.php, app/Http/Controllers/Api/BookController.php, app/Repositories/BookRepositoryEloquent.php, app/Repositories/UserRepositoryEloquent.php, config/model.php, database/migrations/specific_migration/2018_05_14_090722_add_deleted_at_to_owners_table.php
https://dev.framgia.com/redmine/issues/171269
=> Add reputation point when add owner successfully.

app/Contracts/Repositories/BookRepository.php, app/Contracts/Repositories/UserRepository.php, app/Http/Controllers/Api/BookController.php, app/Http/Controllers/Api/UserController.php, app/Repositories/BookRepositoryEloquent.php, app/Repositories/UserRepositoryEloquent.php, config/model.php, database/migrations/book_user_update/2018_05_11_091658_add_approve_to_book_user.php
https://dev.framgia.com/redmine/issues/171271
=> refs task 171271 add point when approve borrow

app/Eloquent/LogReputation.php, app/Eloquent/Review.php, app/Eloquent/Vote.php, app/Http/Controllers/Api/LogController.php, app/Http/Controllers/Api/ReviewController.php, app/Http/Requests/Api/Log/SearchLogRequest.php, app/Providers/AppServiceProvider.php, app/Providers/RepositoryServiceProvider.php, app/Repositories/LogReputationRepositoryEloquent.php, routes/api.php
https://dev.framgia.com/redmine/issues/177064
=> Log to admin

app/Contracts/Repositories/BookRepository.php, app/Http/Controllers/Api/BookController.php, app/Repositories/BookRepositoryEloquent.php
https://dev.framgia.com/issues/182430
search User by name
=> ref task #182430 search user
